name: Health Check for Supabase API

on:
  schedule:
    # Runs once every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API endpoint
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://shyam-ravikumar.vercel.app/api/health
      - name: Check response
        run: |
          response=$(curl -s https://shyam-ravikumar.vercel.app/api/health)
          echo "Response: $response"
